iso:
	#genisoimage  -output seed.iso -volid cidata -joliet -rock user-data meta-data network-config
	#genisoimage  -output seed.iso -volid cidata -joliet -rock user-data meta-data
	genisoimage  -output seed.iso -volid cidata -joliet -rock meta-data
